### ISSUE TITLE
Create a master/slave scheme for rights to allow for wildcards (AUT-8)

### ISSUE THREAD

**Issue by wearefestival** [festivaledu/neo#16]
Rights should categorize themselves with the category itself being the master right of this category, basically allowing the use of wildcards to automatically grant all rights of a particular category. Categories should be able to have subcategories.  
  
Examples:
- `*` always grants all rights because there is no category above
- `neo.*` grants `neo.global.write` and `neo.server.stop` because the wildcard applies to the whole "neo" category
- `neo.global.*` only grants `neo.global.write` because it is limited to "neo.global"

**Comment by vainamov** [comment]
Finished with festivaledu/neo-core@11707b1.
