### ISSUE TITLE
Allow different lifespans for channels (CHN-4)

### ISSUE THREAD

**Issue by wearefestival** [festivaledu/neo#20]
Channels may have one of 4 different lifespan options:

- `custom` The channel will be deleted on a given date
- `volatile` The channel will be deleted as soon as the last person leaves it
- `temporary` The channel will be deleted when the server shuts down
- `permanent` The channel must be deleted by hand

**Comment by vainamov** [comment]
Custom and Volatile have been removed from the specifications.
