### ISSUE TITLE
Add metroUI to the client (FRT-1)

### ISSUE THREAD

**Issue by wearefestival** [festivaledu/neo#35]
Adding metroUI later on requires more work so this should be done in an earlier stage.

**Comment by SniperGER** [comment]
Coding finished with festivaledu/neo-client@021efec, moving on to testing

**Comment by SniperGER** [comment]
Testing finished. A bug was fixed with festivaledu/neo-client@e5d4d3c. Now moving on to Documenting.

**Comment by SniperGER** [comment]
Documentation finished with festivaledu/neo-client@98d40fa. Minor changes in festivaledu/neo-client@e982e57 and festivaledu/neo-client@2eb8fc8.
