### ISSUE TITLE
Add options to create, edit and delete channels

### ISSUE THREAD

**Issue by vainamov** [festivaledu/neo#41]

**Comment by SniperGER** [comment]
Server needs to listen to emitted "channelCreate" events before this feature can be implemented

**Comment by vainamov** [comment]
Creation done with:
https://github.com/festivaledu/neo-core/commit/8fef9359445ca9ddc6cc514458b334a8358dfd22
https://github.com/festivaledu/neo-core/commit/bd39b6b6403d595df67264d9f5f2682fa2bccee9
https://github.com/festivaledu/neo-server/commit/acfb2683e79e424e3aa7b6be0c8a509bc8c3fc17
https://github.com/festivaledu/neo-server/commit/7105210032dea52acd0acb958877db6381110924
https://github.com/festivaledu/neo-client/commit/8d8c5504877d4adfedc20e60adeaf9275eebf6c4

**Comment by vainamov** [comment]
Edit done with https://github.com/festivaledu/neo-core/commit/eb797fc16b12b8b5ef1d5ea3398cdb6df292e21b and https://github.com/festivaledu/neo-client/commit/6eb3a7031f7a56689c258d2eafbf714c77b8e6b7.

**Comment by vainamov** [comment]
Done by adding deletion with https://github.com/festivaledu/neo-core/commit/ea42d4866dc6f82b39e331b0bfb0cdaa07cf571b, https://github.com/festivaledu/neo-server/commit/cb7c3ce0d35ebd138c2b34abe121c27faac17841 and https://github.com/festivaledu/neo-client/commit/34ada6a692dcbb459ce32a0209d6337fbbc00a31.
