### ISSUE TITLE
Add moderation functionality (Kick/Ban)

### ISSUE THREAD

**Issue by vainamov** [festivaledu/neo#48]

**Comment by vainamov** [comment]
Began work in https://github.com/festivaledu/neo-core/commit/05cd7efab346a5eacca0cb825e795152145aa95b, https://github.com/festivaledu/neo-server/commit/45ae0822f86e6ef8ebee33ad12eb91b48a92bf78 and https://github.com/festivaledu/neo-client/commit/0b2b932b43e0942d966b335bf798c3d86a0bb6a6.

**Comment by SniperGER** [comment]
Server is only sending "kick" punishments, regardless of what the chosen punishment is

**Comment by vainamov** [comment]
Done with https://github.com/festivaledu/neo-core/commit/637f33afd808c95ecd679f9bd3dd298904d3ba6b, https://github.com/festivaledu/neo-server/commit/0a3a8df590c3dd3b41455f4b4b788e8210d2bff7 and https://github.com/festivaledu/neo-client/commit/98a8c5b8f65f988a1e272ecff89052dea336577e.
