### ISSUE TITLE
Add mentions

### ISSUE THREAD

**Issue by vainamov** [festivaledu/neo#51]

**Comment by SniperGER** [comment]
Still missing server events before I can implement client notifications

**Comment by SniperGER** [comment]
Mention notifications implemented with festivaledu/neo-client@f5e677a. Awaiting revised ```Input``` packages on server side

**Comment by vainamov** [comment]
Done with:
https://github.com/festivaledu/neo-core/commit/f4af2852031fe8fb3487b1db4d3d1fa763ae2b1b
https://github.com/festivaledu/neo-core/commit/8fef9359445ca9ddc6cc514458b334a8358dfd22
https://github.com/festivaledu/neo-server/commit/0da4747fc8e84a2f5ebfd4f7cf4ddef3a6dec9a4
https://github.com/festivaledu/neo-server/commit/acfb2683e79e424e3aa7b6be0c8a509bc8c3fc17
https://github.com/festivaledu/neo-client/commit/6fcfc5c85c6332810c39db650fcd39e69a3025fc
https://github.com/festivaledu/neo-client/commit/70fa9d0a48f79352f398af2411e3e942e8d6af6f
https://github.com/festivaledu/neo-client/commit/7fc1dcc221a0feb1a5ab096315e3ce1697a26758
