### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by vainamov** [festivaledu/neo#54]
Use MetroUI notifications in the web and on Electron when the app is currently active.
Use native notifications from Windows and macOS on Electron when the app is in the background.

**Comment by vainamov** [comment]
Added with https://github.com/festivaledu/neo-client/commit/d4167b97841b4b2ef79d90358f903c137f78fda6.

**Comment by SniperGER** [comment]
Notification delegate (browser/desktop) following
