### ISSUE TITLE
Transfer AES data using RSA encryption (CRY-3)

### ISSUE THREAD

**Issue by wearefestival** [festivaledu/neo#6]
The server should generate a set of RSA keys for each session. The public key is then handed to the client so that the client can encrypt his AES data.

**Comment by vainamov** [comment]
- [X] Server
- [ ] Client

**Comment by vainamov** [comment]
There is no working library or method to encrypt data in JavaScript in a way that it is encryptable in C#. Therefore this is impossible as of now.

**Comment by vainamov** [comment]
Removed from the requirements due to schedule problems.
